# Generated by Django 4.2.20 on 2025-04-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_sharing', '0002_alter_content_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='content',
            name='visibility',
            field=models.CharField(choices=[('public', 'Herkese Açık'), ('followers', 'Sadece Takipçiler'), ('private', 'Özel')], default='public', max_length=20),
        ),
    ]
